"""Initial commit

Revision ID: 22fa2341eccf
Revises: 
Create Date: 2025-12-01 08:51:55.450698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '22fa2341eccf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('books_ibfk_1'), 'books', type_='foreignkey')
    op.drop_column('books', 'author_id')
    op.drop_constraint(op.f('reviews_ibfk_1'), 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'book_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('book_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('reviews_ibfk_1'), 'reviews', 'books', ['book_id'], ['id'])
    op.add_column('books', sa.Column('author_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('books_ibfk_1'), 'books', 'authors', ['author_id'], ['id'])
    # ### end Alembic commands ###
