"""new fk

Revision ID: 8e202ac241e6
Revises: 0243a2ddfdc6
Create Date: 2025-12-02 11:06:15.885480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e202ac241e6'
down_revision: Union[str, Sequence[str], None] = '0243a2ddfdc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('book_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'reviews', 'books', ['book_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'book_id')
    # ### end Alembic commands ###
