"""add relations and new columns

Revision ID: 95e1e7ce0141
Revises: 8e202ac241e6
Create Date: 2025-12-02 15:00:27.806203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95e1e7ce0141'
down_revision: Union[str, Sequence[str], None] = '8e202ac241e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'is_deleted')
    # ### end Alembic commands ###
